package com.guidewire;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630329
 * 2021-12-13T11:09:47.702-05:00
 * Generated source version: 3.1.5.redhat-630329
 * 
 */
@WebService(targetNamespace = "http://guidewire.com/", name = "MitchellMessagingAPIPortType")
@XmlSeeAlso({com.guidewire.ws.soapheaders.ObjectFactory.class})
public interface MitchellMessagingAPIPortType {
}
