
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.guidewire;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630329
 * 2021-12-13T11:09:47.671-05:00
 * Generated source version: 3.1.5.redhat-630329
 * 
 */

@javax.jws.WebService(
                      serviceName = "MitchellMessagingAPI",
                      portName = "MitchellMessagingAPISoap11Port",
                      targetNamespace = "http://guidewire.com/",
                      wsdlLocation = "classpath:xsds/gwcc/gw_messagingAPI.wsdl",
                      endpointInterface = "com.guidewire.MitchellMessagingAPIPortType")
                      
public class MitchellMessagingAPISoap11PortImpl implements MitchellMessagingAPIPortType {

    private static final Logger LOG = Logger.getLogger(MitchellMessagingAPISoap11PortImpl.class.getName());

}
