package com.guidewire;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630329
 * 2021-12-13T11:09:47.712-05:00
 * Generated source version: 3.1.5.redhat-630329
 * 
 */
@WebServiceClient(name = "MitchellMessagingAPI", 
                  wsdlLocation = "classpath:xsds/gwcc/gw_messagingAPI.wsdl",
                  targetNamespace = "http://guidewire.com/") 
public class MitchellMessagingAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://guidewire.com/", "MitchellMessagingAPI");
    public final static QName MitchellMessagingAPISoap12Port = new QName("http://guidewire.com/", "MitchellMessagingAPISoap12Port");
    public final static QName MitchellMessagingAPISoap11Port = new QName("http://guidewire.com/", "MitchellMessagingAPISoap11Port");
    static {
        URL url = MitchellMessagingAPI.class.getClassLoader().getResource("xsds/gwcc/gw_messagingAPI.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(MitchellMessagingAPI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:xsds/gwcc/gw_messagingAPI.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public MitchellMessagingAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MitchellMessagingAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MitchellMessagingAPI() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MitchellMessagingAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MitchellMessagingAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MitchellMessagingAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MitchellMessagingAPIPortType
     */
    @WebEndpoint(name = "MitchellMessagingAPISoap12Port")
    public MitchellMessagingAPIPortType getMitchellMessagingAPISoap12Port() {
        return super.getPort(MitchellMessagingAPISoap12Port, MitchellMessagingAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MitchellMessagingAPIPortType
     */
    @WebEndpoint(name = "MitchellMessagingAPISoap12Port")
    public MitchellMessagingAPIPortType getMitchellMessagingAPISoap12Port(WebServiceFeature... features) {
        return super.getPort(MitchellMessagingAPISoap12Port, MitchellMessagingAPIPortType.class, features);
    }


    /**
     *
     * @return
     *     returns MitchellMessagingAPIPortType
     */
    @WebEndpoint(name = "MitchellMessagingAPISoap11Port")
    public MitchellMessagingAPIPortType getMitchellMessagingAPISoap11Port() {
        return super.getPort(MitchellMessagingAPISoap11Port, MitchellMessagingAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MitchellMessagingAPIPortType
     */
    @WebEndpoint(name = "MitchellMessagingAPISoap11Port")
    public MitchellMessagingAPIPortType getMitchellMessagingAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(MitchellMessagingAPISoap11Port, MitchellMessagingAPIPortType.class, features);
    }

}
