package org.openuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630329
 * 2022-01-11T23:26:42.322-05:00
 * Generated source version: 3.1.5.redhat-630329
 * 
 */
@WebServiceClient(name = "FileReceiverService", 
                  wsdlLocation = "classpath:xsds/Generic-FileReceiverService.wsdl",
                  targetNamespace = "http://www.openuri.org/") 
public class FileReceiverService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.openuri.org/", "FileReceiverService");
    public final static QName FileReceiverServiceSoap = new QName("http://www.openuri.org/", "FileReceiverServiceSoap");
    static {
        URL url = FileReceiverService.class.getClassLoader().getResource("xsds/Generic-FileReceiverService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(FileReceiverService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:xsds/Generic-FileReceiverService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public FileReceiverService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileReceiverService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileReceiverService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FileReceiverService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FileReceiverService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FileReceiverService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns FileReceiverServiceSoap
     */
    @WebEndpoint(name = "FileReceiverServiceSoap")
    public FileReceiverServiceSoap getFileReceiverServiceSoap() {
        return super.getPort(FileReceiverServiceSoap, FileReceiverServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileReceiverServiceSoap
     */
    @WebEndpoint(name = "FileReceiverServiceSoap")
    public FileReceiverServiceSoap getFileReceiverServiceSoap(WebServiceFeature... features) {
        return super.getPort(FileReceiverServiceSoap, FileReceiverServiceSoap.class, features);
    }

}
