package org.openuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630329
 * 2022-01-11T23:26:42.307-05:00
 * Generated source version: 3.1.5.redhat-630329
 * 
 */
@WebService(targetNamespace = "http://www.openuri.org/", name = "FileReceiverServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FileReceiverServiceSoap {

    @WebMethod(action = "http://www.openuri.org/receiveFile")
    @RequestWrapper(localName = "receiveFile", targetNamespace = "http://www.openuri.org/", className = "org.openuri.ReceiveFile")
    @ResponseWrapper(localName = "receiveFileResponse", targetNamespace = "http://www.openuri.org/", className = "org.openuri.ReceiveFileResponse")
    @WebResult(name = "receiveFileResult", targetNamespace = "http://www.openuri.org/")
    public java.lang.String receiveFile(
        @WebParam(name = "payload", targetNamespace = "http://www.openuri.org/")
        java.lang.String payload
    );
}
