
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.openuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630329
 * 2022-01-11T23:26:42.225-05:00
 * Generated source version: 3.1.5.redhat-630329
 * 
 */

@javax.jws.WebService(
                      serviceName = "FileReceiverService",
                      portName = "FileReceiverServiceSoap",
                      targetNamespace = "http://www.openuri.org/",
                      wsdlLocation = "classpath:xsds/Generic-FileReceiverService.wsdl",
                      endpointInterface = "org.openuri.FileReceiverServiceSoap")
                      
public class FileReceiverServiceSoapImpl implements FileReceiverServiceSoap {

    private static final Logger LOG = Logger.getLogger(FileReceiverServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see org.openuri.FileReceiverServiceSoap#receiveFile(java.lang.String  payload )*
     */
    public java.lang.String receiveFile(java.lang.String payload) { 
        LOG.info("Executing operation receiveFile");
        System.out.println(payload);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
