package com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-26T09:29:18.051-04:00
 * Generated source version: 3.1.5.redhat-630187
 * 
 */
@WebService(targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", name = "DigitalNotificationServiceAPIPortType")
@XmlSeeAlso({ObjectFactory.class, com.guidewire.ws.soapheaders.ObjectFactory.class, com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.schema.digitalnotificationserviceapi.ObjectFactory.class})
@HandlerChain(file = "handler-chain.xml")
public interface DigitalNotificationServiceAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "updateNotificationStatus", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", className = "com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatus")
    @ResponseWrapper(localName = "updateNotificationStatusResponse", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", className = "com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI")
    public com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatusResponse.Return updateNotificationStatus(
        @WebParam(name = "notificationStatusUpdateRq", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI")
        com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatus.NotificationStatusUpdateRq notificationStatusUpdateRq
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "unsubscribeNotification", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", className = "com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotification")
    @ResponseWrapper(localName = "unsubscribeNotificationResponse", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", className = "com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotificationResponse")
    @WebResult(name = "return", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI")
    public com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotificationResponse.Return unsubscribeNotification(
        @WebParam(name = "unsubscribeRq", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI")
        com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotification.UnsubscribeRq unsubscribeRq
    ) throws WsiAuthenticationException_Exception;
}
