
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-26T09:29:17.787-04:00
 * Generated source version: 3.1.5.redhat-630187
 * 
 */

@javax.jws.WebService(
                      serviceName = "DigitalNotificationServiceAPI",
                      portName = "DigitalNotificationServiceAPISoap11Port",
                      targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI",
                      wsdlLocation = "Y:%5cWorkspace%5cCOP%5cesb-stub-webserviceconsumer/../src/main/resources/wsdl/DigitalNotificationServiceAPI_1.wsdl",
                      endpointInterface = "com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.DigitalNotificationServiceAPIPortType")
                      
public class DigitalNotificationServiceAPISoap11PortImpl implements DigitalNotificationServiceAPIPortType {

    private static final Logger LOG = Logger.getLogger(DigitalNotificationServiceAPISoap11PortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.DigitalNotificationServiceAPIPortType#updateNotificationStatus(com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatus.NotificationStatusUpdateRq  notificationStatusUpdateRq )*
     */
    public com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatusResponse.Return updateNotificationStatus(com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatus.NotificationStatusUpdateRq notificationStatusUpdateRq) throws WsiAuthenticationException_Exception    { 
        LOG.info("Executing operation updateNotificationStatus");
        System.out.println(notificationStatusUpdateRq);
        try {
            com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UpdateNotificationStatusResponse.Return _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WsiAuthenticationException_Exception("WsiAuthenticationException...");
    }

    /* (non-Javadoc)
     * @see com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.DigitalNotificationServiceAPIPortType#unsubscribeNotification(com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotification.UnsubscribeRq  unsubscribeRq )*
     */
    public com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotificationResponse.Return unsubscribeNotification(com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotification.UnsubscribeRq unsubscribeRq) throws WsiAuthenticationException_Exception    { 
        LOG.info("Executing operation unsubscribeNotification");
        System.out.println(unsubscribeRq);
        try {
            com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.UnsubscribeNotificationResponse.Return _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WsiAuthenticationException_Exception("WsiAuthenticationException...");
    }

}
