package com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-26T09:29:18.058-04:00
 * Generated source version: 3.1.5.redhat-630187
 * 
 */
@WebServiceClient(name = "DigitalNotificationServiceAPI", 
                  wsdlLocation = "file:/Y:/Workspace/COP/esb-stub-webserviceconsumer/src/main/resources/wsdl/DigitalNotificationServiceAPI_1.wsdl",
                  targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI") 
public class DigitalNotificationServiceAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", "DigitalNotificationServiceAPI");
    public final static QName DigitalNotificationServiceAPISoap12Port = new QName("http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", "DigitalNotificationServiceAPISoap12Port");
    public final static QName DigitalNotificationServiceAPISoap11Port = new QName("http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI", "DigitalNotificationServiceAPISoap11Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/Y:/Workspace/COP/esb-stub-webserviceconsumer/src/main/resources/wsdl/DigitalNotificationServiceAPI_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DigitalNotificationServiceAPI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Y:/Workspace/COP/esb-stub-webserviceconsumer/src/main/resources/wsdl/DigitalNotificationServiceAPI_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DigitalNotificationServiceAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DigitalNotificationServiceAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DigitalNotificationServiceAPI() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DigitalNotificationServiceAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DigitalNotificationServiceAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DigitalNotificationServiceAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DigitalNotificationServiceAPIPortType
     */
    @WebEndpoint(name = "DigitalNotificationServiceAPISoap12Port")
    public DigitalNotificationServiceAPIPortType getDigitalNotificationServiceAPISoap12Port() {
        return super.getPort(DigitalNotificationServiceAPISoap12Port, DigitalNotificationServiceAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigitalNotificationServiceAPIPortType
     */
    @WebEndpoint(name = "DigitalNotificationServiceAPISoap12Port")
    public DigitalNotificationServiceAPIPortType getDigitalNotificationServiceAPISoap12Port(WebServiceFeature... features) {
        return super.getPort(DigitalNotificationServiceAPISoap12Port, DigitalNotificationServiceAPIPortType.class, features);
    }


    /**
     *
     * @return
     *     returns DigitalNotificationServiceAPIPortType
     */
    @WebEndpoint(name = "DigitalNotificationServiceAPISoap11Port")
    public DigitalNotificationServiceAPIPortType getDigitalNotificationServiceAPISoap11Port() {
        return super.getPort(DigitalNotificationServiceAPISoap11Port, DigitalNotificationServiceAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigitalNotificationServiceAPIPortType
     */
    @WebEndpoint(name = "DigitalNotificationServiceAPISoap11Port")
    public DigitalNotificationServiceAPIPortType getDigitalNotificationServiceAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(DigitalNotificationServiceAPISoap11Port, DigitalNotificationServiceAPIPortType.class, features);
    }

}
