
package com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-26T09:29:18.045-04:00
 * Generated source version: 3.1.5.redhat-630187
 */

@WebFault(name = "WsiAuthenticationException", targetNamespace = "http://www.avivacanada.com/cc/ws/com/avivacanada/integration/webservice/digitalnotification/DigitalNotificationServiceAPI")
public class WsiAuthenticationException_Exception extends Exception {
    
    private com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.WsiAuthenticationException wsiAuthenticationException;

    public WsiAuthenticationException_Exception() {
        super();
    }
    
    public WsiAuthenticationException_Exception(String message) {
        super(message);
    }
    
    public WsiAuthenticationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WsiAuthenticationException_Exception(String message, com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.WsiAuthenticationException wsiAuthenticationException) {
        super(message);
        this.wsiAuthenticationException = wsiAuthenticationException;
    }

    public WsiAuthenticationException_Exception(String message, com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.WsiAuthenticationException wsiAuthenticationException, Throwable cause) {
        super(message, cause);
        this.wsiAuthenticationException = wsiAuthenticationException;
    }

    public com.avivacanada.cc.ws.com.avivacanada.integration.webservice.digitalnotification.digitalnotificationserviceapi.WsiAuthenticationException getFaultInfo() {
        return this.wsiAuthenticationException;
    }
}
