package com.avivacanada.services.fuse.notification.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-20T13:42:07.714-04:00
 * Generated source version: 3.1.5.redhat-630187
 * 
 */
@WebServiceClient(name = "NotificationService", 
                  wsdlLocation = "file:/Y:/Workspace/COP/esb-stub-webserviceprovider/src/main/resources/wsdl/Notification.wsdl",
                  targetNamespace = "http://www.avivacanada.com/services/fuse/notification/v1") 
public class NotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.avivacanada.com/services/fuse/notification/v1", "NotificationService");
    public final static QName NotificationPort = new QName("http://www.avivacanada.com/services/fuse/notification/v1", "NotificationPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Y:/Workspace/COP/esb-stub-webserviceprovider/src/main/resources/wsdl/Notification.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Y:/Workspace/COP/esb-stub-webserviceprovider/src/main/resources/wsdl/Notification.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NotificationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NotificationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NotificationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Notification
     */
    @WebEndpoint(name = "NotificationPort")
    public Notification getNotificationPort() {
        return super.getPort(NotificationPort, Notification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Notification
     */
    @WebEndpoint(name = "NotificationPort")
    public Notification getNotificationPort(WebServiceFeature... features) {
        return super.getPort(NotificationPort, Notification.class, features);
    }

}
