
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.avivacanada.services.fuse.notification.v1;

import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-20T13:42:07.514-04:00
 * Generated source version: 3.1.5.redhat-630187
 * 
 */

@javax.jws.WebService(
                      serviceName = "NotificationService",
                      portName = "NotificationPort",
                      targetNamespace = "http://www.avivacanada.com/services/fuse/notification/v1",
                      wsdlLocation = "Y:%5cWorkspace%5cCOP%5cesb-stub-webserviceprovider/../src/main/resources/wsdl/Notification.wsdl",
                      endpointInterface = "com.avivacanada.services.fuse.notification.v1.Notification")
                      
public class NotificationPortImpl implements Notification {

    private static final Logger LOG = Logger.getLogger(NotificationPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.avivacanada.services.fuse.notification.v1.Notification#sendPhoneNotification(com.avivacanada.services.fuse.notification.v1.SendPhoneNotificationRequest  sendPhoneNotificationRq )*
     */
    public com.avivacanada.services.fuse.notification.v1.SendPhoneNotificationResponse sendPhoneNotification(SendPhoneNotificationRequest sendPhoneNotificationRq) throws SOAPServiceException    { 
        LOG.info("Executing operation sendPhoneNotification");
        System.out.println(sendPhoneNotificationRq);
        try {
            com.avivacanada.services.fuse.notification.v1.SendPhoneNotificationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPServiceException("SOAPServiceException...");
    }

}
