package com.avivacanada.services.fuse.notification.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-20T13:42:07.709-04:00
 * Generated source version: 3.1.5.redhat-630187
 * 
 */
@WebService(targetNamespace = "http://www.avivacanada.com/services/fuse/notification/v1", name = "notification")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Notification {

    @WebMethod
    @WebResult(name = "sendPhoneNotificationRs", targetNamespace = "http://www.avivacanada.com/services/fuse/notification/v1", partName = "sendPhoneNotificationRs")
    public SendPhoneNotificationResponse sendPhoneNotification(
        @WebParam(partName = "sendPhoneNotificationRq", name = "sendPhoneNotificationRq", targetNamespace = "http://www.avivacanada.com/services/fuse/notification/v1")
        SendPhoneNotificationRequest sendPhoneNotificationRq
    ) throws SOAPServiceException;
}
