//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 04:30:49 PM EST
//


package com.avivacanada.services.fuse.notification.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhoneType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PhoneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number" type="{http://www.avivacanada.com/services/fuse/notification/v1}PhoneNumber"/>
 *         &lt;element name="category" type="{http://www.avivacanada.com/services/fuse/notification/v1}PhoneCategoryType"/>
 *         &lt;element name="contactId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneType", propOrder = {
        "number",
        "category"
        /*,
        "contactId"*/
})
public class PhoneType {

    @XmlElement(required = true)
    protected String number;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PhoneCategoryType category;
    //protected String contactId;

    /**
     * Gets the value of the number property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return
     *     possible object is
     *     {@link PhoneCategoryType }
     *
     */
    public PhoneCategoryType getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value
     *     allowed object is
     *     {@link PhoneCategoryType }
     *
     */
    public void setCategory(PhoneCategoryType value) {
        this.category = value;
    }

    /**
     * Gets the value of the contactId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
   /* public String getContactId() {
        return contactId;
    }

    *//**
     * Sets the value of the contactId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     *//*
    public void setContactId(String value) {
        this.contactId = value;
    }*/

}
