
package com.avivacanada.services.fuse.notification.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5.redhat-630187
 * 2018-09-20T13:42:07.703-04:00
 * Generated source version: 3.1.5.redhat-630187
 */

@WebFault(name = "SOAPServiceException", targetNamespace = "http://www.avivacanada.com/services/fuse/notification/v1")
public class SOAPServiceException extends Exception {
	private static final long serialVersionUID = 1L;    
    private com.avivacanada.services.fuse.notification.v1.DetailException soapServiceException;

    public SOAPServiceException() {
        super();
    }
    
    public SOAPServiceException(String message) {
        super(message);
    }
    
    public SOAPServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public SOAPServiceException(String message, com.avivacanada.services.fuse.notification.v1.DetailException soapServiceException) {
        super(message);
        this.soapServiceException = soapServiceException;
    }

    public SOAPServiceException(String message, com.avivacanada.services.fuse.notification.v1.DetailException soapServiceException, Throwable cause) {
        super(message, cause);
        this.soapServiceException = soapServiceException;
    }

    public com.avivacanada.services.fuse.notification.v1.DetailException getFaultInfo() {
        return this.soapServiceException;
    }
}
