//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.01 at 12:00:23 PM EST 
//


package com.mitchell.schemas.mitchellclaimevent;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mitchell.schemas.mitchellclaimevent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mitchell.schemas.mitchellclaimevent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MitchellClaimEvent }
     * 
     */
    public MitchellClaimEvent createMitchellClaimEvent() {
        return new MitchellClaimEvent();
    }

    /**
     * Create an instance of {@link MitchellClaimEvent.EventDetails }
     * 
     */
    public MitchellClaimEvent.EventDetails createMitchellClaimEventEventDetails() {
        return new MitchellClaimEvent.EventDetails();
    }

    /**
     * Create an instance of {@link MitchellClaimEventList }
     * 
     */
    public MitchellClaimEventList createMitchellClaimEventList() {
        return new MitchellClaimEventList();
    }

    /**
     * Create an instance of {@link MitchellClaimEvent.User }
     * 
     */
    public MitchellClaimEvent.User createMitchellClaimEventUser() {
        return new MitchellClaimEvent.User();
    }

    /**
     * Create an instance of {@link MitchellClaimEvent.ApplicationURIList }
     * 
     */
    public MitchellClaimEvent.ApplicationURIList createMitchellClaimEventApplicationURIList() {
        return new MitchellClaimEvent.ApplicationURIList();
    }

    /**
     * Create an instance of {@link MitchellClaimEvent.EventDetails.NameValuePair }
     * 
     */
    public MitchellClaimEvent.EventDetails.NameValuePair createMitchellClaimEventEventDetailsNameValuePair() {
        return new MitchellClaimEvent.EventDetails.NameValuePair();
    }

}
